theme: jekyll-theme-tactile
excerpt_separator: '<!-- more -->'
base: http://impresso-project.ch
title: impresso
lang: en
languages: ["en", "fr", "de"]

publisher:
  name: impresso

contacts:
  email: info @ impresso-project [dot] ch
  twitter:
    url: https://twitter.com/impressoproject
    name: "@impressoproject"
  github:
    url: https://github.com/impresso
    name: impresso


collections:
  agenda:
    output: true
    permalink: /:collection/:path/
  people:
    output: true
    permalink: /:collection/:path/
  partners:
    output: true
    permalink: /:collection/:path/
  glossary:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: "agenda"
    values:
      layout: "agenda"
  - scope:
      path: ""
      type: "glossary"
    values:
      layout: "glossaryItem"
